---
"on":
  push:
    paths-ignore:
      - "**.md"
      - doc/*
  pull_request:
    paths-ignore:
      - "**.md"
      - doc/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xmake-io/github-action-setup-xmake@v1
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{secrets.GITHUB_TOKEN}}
      - run: |
          nix-env -f '<nixpkgs>' -iA \
            llvmPackages_latest.llvm.dev llvmPackages_latest.llvm.lib \
            llvmPackages_latest.libclang.dev llvmPackages_latest.libclang.lib
      - uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
          # https://github.com/cachix/install-nix-action/issues/247
          NIX_PROFILES: /home/runner/.local/state/nix/profiles/profile
          CXXFLAGS: >
            -isystem/home/runner/.local/state/nix/profiles/profile/include
          LDFLAGS: >
            -L/home/runner/.local/state/nix/profiles/profile/lib
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          extra_luarocks_args: |
            --force
          version: scm
          template: template.rockspec
      - uses: nvim-neorocks/luarocks-tag-release@v5
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
          NIX_PROFILES: /home/runner/.local/state/nix/profiles/profile
          CXXFLAGS: >
            -isystem/home/runner/.local/state/nix/profiles/profile/include
          LDFLAGS: >
            -L/home/runner/.local/state/nix/profiles/profile/lib
        if: startsWith(github.ref, 'refs/tags/')
        with:
          extra_luarocks_args: |
            --force
          template: template.rockspec
